
import React from 'react';
import { Button } from '@/components/ui/button';
import { Download, Mail, Edit, Save } from 'lucide-react';

interface PreviewStepProps {
  payslipData: any;
  setPayslipData: (data: any) => void;
  isParentMode: boolean;
  selectedChild: any;
}

export const PreviewStep = ({ payslipData, isParentMode, selectedChild }: PreviewStepProps) => {
  const totalDeductions = payslipData.deductions.reduce((sum: number, d: any) => sum + d.amount, 0);
  const netPay = payslipData.grossPay - totalDeductions;

  const formatPeriod = (period: string) => {
    if (!period) return '';
    const [year, month] = period.split('-');
    const date = new Date(parseInt(year), parseInt(month) - 1);
    return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  };

  return (
    <div className="space-y-6">
      <div className="text-center mb-6">
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Payslip Preview</h2>
        <p className="text-gray-600">Review your payslip before saving</p>
      </div>

      {/* Payslip Preview */}
      <div className="bg-white border-2 border-gray-200 rounded-lg p-6 shadow-sm">
        {/* Header */}
        <div className="text-center border-b border-gray-200 pb-4 mb-6">
          <h1 className="text-2xl font-bold text-blue-900">PAYSLIP</h1>
          <p className="text-gray-600 mt-1">Pay Period: {formatPeriod(payslipData.period)}</p>
          <p className="text-gray-600 text-sm">{payslipData.companyName}</p>
        </div>

        {/* Employee Info */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-gray-800 mb-2">Employee Information</h2>
          <div className="bg-gray-50 rounded p-3">
            <p><span className="font-medium">Name:</span> {payslipData.name}</p>
            <p><span className="font-medium">Pay Period:</span> {formatPeriod(payslipData.period)}</p>
            {isParentMode && selectedChild && (
              <p><span className="font-medium">Created for:</span> {selectedChild.name}</p>
            )}
          </div>
        </div>

        {/* Earnings */}
        <div className="mb-6">
          <h2 className="text-lg font-semibold text-gray-800 mb-2">Earnings</h2>
          <div className="bg-green-50 rounded p-3">
            <div className="flex justify-between">
              <span>Gross Pay</span>
              <span className="font-medium">${payslipData.grossPay.toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Deductions */}
        {payslipData.deductions.length > 0 && (
          <div className="mb-6">
            <h2 className="text-lg font-semibold text-gray-800 mb-2">Deductions</h2>
            <div className="bg-red-50 rounded p-3 space-y-2">
              {payslipData.deductions.map((deduction: any) => (
                <div key={deduction.id} className="flex justify-between">
                  <span>
                    {deduction.name} 
                    <span className="text-sm text-gray-500 ml-1">
                      ({deduction.type === 'percentage' ? `${deduction.value}%` : 'Fixed'})
                    </span>
                  </span>
                  <span className="font-medium">-${deduction.amount.toFixed(2)}</span>
                </div>
              ))}
              <div className="border-t border-red-200 pt-2 flex justify-between font-semibold">
                <span>Total Deductions</span>
                <span>-${totalDeductions.toFixed(2)}</span>
              </div>
            </div>
          </div>
        )}

        {/* Net Pay */}
        <div className="border-t border-gray-200 pt-4">
          <div className="bg-blue-50 rounded p-4">
            <div className="flex justify-between items-center">
              <span className="text-xl font-bold text-blue-900">NET PAY</span>
              <span className="text-2xl font-bold text-blue-900">${netPay.toFixed(2)}</span>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center text-sm text-gray-500 mt-6 pt-4 border-t border-gray-200">
          Generated by SlipSim • {new Date().toLocaleDateString()}
        </div>
      </div>

      {/* Future Action Buttons (for later implementation) */}
      <div className="space-y-3 opacity-50">
        <Button disabled className="w-full bg-blue-600 hover:bg-blue-700">
          <Download className="h-4 w-4 mr-2" />
          Download PDF (Coming Soon)
        </Button>
        
        <Button disabled variant="outline" className="w-full">
          <Mail className="h-4 w-4 mr-2" />
          Email Payslip (Coming Soon)
        </Button>
      </div>

      {isParentMode && (
        <div className="bg-green-50 border border-green-200 rounded-lg p-4">
          <h3 className="font-medium text-green-800 mb-2">🎉 Great Job!</h3>
          <p className="text-sm text-green-700">
            You've created a professional payslip! This shows how money flows from what you earn 
            to what you actually take home. Understanding this helps with budgeting and financial planning.
          </p>
        </div>
      )}
    </div>
  );
};
