
import React from 'react';

export const PayslipFooter = () => {
  return (
    <div className="text-center text-sm text-gray-500 mt-6 pt-4 border-t border-gray-200">
      {/* Generated by SlipSim • {new Date().toLocaleDateString()} */}
    </div>
  );
};
