// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bknslgbxupkuifihjmqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrbnNsZ2J4dXBrdWlmaWhqbXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MTA0OTMsImV4cCI6MjA2NjM4NjQ5M30.GxXPIFp8vmwsTBbA77VVJWVNcEJybp8sI7iifzGuMDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);